project:
  type: website
  output-dir: docs

website:
  title: "Peter Atkins"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: CV.qmd
        text: CV
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  python:
    python-path: /opt/anaconda3/bin/python