<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Peter Atkins">
<meta name="dcterms.date" content="2024-04-28">

<title>Peter Atkins - Poisson Regression Examples</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Peter Atkins</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../CV.html"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#blueprinty-case-study" id="toc-blueprinty-case-study" class="nav-link active" data-scroll-target="#blueprinty-case-study">Blueprinty Case Study</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#histogram-and-means-of-number-of-patents-by-customer-status" id="toc-histogram-and-means-of-number-of-patents-by-customer-status" class="nav-link" data-scroll-target="#histogram-and-means-of-number-of-patents-by-customer-status">Histogram and Means of Number of Patents by Customer Status</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  <li><a href="#regional-and-age-differences-by-customer-status" id="toc-regional-and-age-differences-by-customer-status" class="nav-link" data-scroll-target="#regional-and-age-differences-by-customer-status">Regional and Age Differences by Customer Status</a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1"></a></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2"></a></li>
  <li><a href="#estimation-of-simple-poisson-model" id="toc-estimation-of-simple-poisson-model" class="nav-link" data-scroll-target="#estimation-of-simple-poisson-model">Estimation of Simple Poisson Model</a></li>
  <li><a href="#section-3" id="toc-section-3" class="nav-link" data-scroll-target="#section-3"></a></li>
  <li><a href="#log-likelihoods" id="toc-log-likelihoods" class="nav-link" data-scroll-target="#log-likelihoods">Log-Likelihoods</a></li>
  <li><a href="#section-4" id="toc-section-4" class="nav-link" data-scroll-target="#section-4"></a></li>
  <li><a href="#lambda-vs.-likelihood" id="toc-lambda-vs.-likelihood" class="nav-link" data-scroll-target="#lambda-vs.-likelihood">lambda vs.&nbsp;Likelihood</a></li>
  <li><a href="#section-5" id="toc-section-5" class="nav-link" data-scroll-target="#section-5"></a></li>
  <li><a href="#mle-estimation-via-likelihood-optimization" id="toc-mle-estimation-via-likelihood-optimization" class="nav-link" data-scroll-target="#mle-estimation-via-likelihood-optimization">MLE Estimation via likelihood optimization</a></li>
  <li><a href="#section-6" id="toc-section-6" class="nav-link" data-scroll-target="#section-6"></a></li>
  <li><a href="#section-7" id="toc-section-7" class="nav-link" data-scroll-target="#section-7"></a></li>
  <li><a href="#estimation-of-poisson-regression-model" id="toc-estimation-of-poisson-regression-model" class="nav-link" data-scroll-target="#estimation-of-poisson-regression-model">Estimation of Poisson Regression Model</a></li>
  <li><a href="#section-8" id="toc-section-8" class="nav-link" data-scroll-target="#section-8"></a></li>
  <li><a href="#standard-errors-using-python-sm.glm-function" id="toc-standard-errors-using-python-sm.glm-function" class="nav-link" data-scroll-target="#standard-errors-using-python-sm.glm-function">Standard Errors using Python sm.GLM() function</a></li>
  <li><a href="#section-9" id="toc-section-9" class="nav-link" data-scroll-target="#section-9"></a></li>
  <li><a href="#interpretation-of-results" id="toc-interpretation-of-results" class="nav-link" data-scroll-target="#interpretation-of-results">Interpretation of Results</a></li>
  </ul></li>
  <li><a href="#airbnb-case-study" id="toc-airbnb-case-study" class="nav-link" data-scroll-target="#airbnb-case-study">AirBnB Case Study</a>
  <ul class="collapse">
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1">Introduction</a></li>
  <li><a href="#summary-of-results" id="toc-summary-of-results" class="nav-link" data-scroll-target="#summary-of-results">Summary of Results</a></li>
  <li><a href="#section-10" id="toc-section-10" class="nav-link" data-scroll-target="#section-10"></a></li>
  <li><a href="#interpretation-of-results-1" id="toc-interpretation-of-results-1" class="nav-link" data-scroll-target="#interpretation-of-results-1">interpretation of Results</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Poisson Regression Examples</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Peter Atkins </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 28, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="blueprinty-case-study" class="level2">
<h2 class="anchored" data-anchor-id="blueprinty-case-study">Blueprinty Case Study</h2>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>Blueprinty is a small firm that makes software for developing blueprints specifically for submitting patent applications to the US patent office. Their marketing team would like to make the claim that patent applicants using Blueprinty’s software are more successful in getting their patent applications approved. Ideal data to study such an effect might include the success rate of patent applications before using Blueprinty’s software and after using it. Unfortunately, such data is not available.</p>
<p>However, Blueprinty has collected data on 1,500 mature (non-startup) engineering firms. The data include each firm’s number of patents awarded over the last 5 years, regional location, age since incorporation, and whether or not the firm uses Blueprinty’s software. The marketing team would like to use this data to make the claim that firms using Blueprinty’s software are more successful in getting their patent applications approved.</p>
</section>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<em>todo: Read in data.</em>
<details>
<summary>
Code
</summary>
<div id="96c79d1b" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize_scalar</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>airbnb_data <span class="op">=</span> <span class="st">"/Users/peteratkins/Downloads/airbnb.csv"</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>blueprinty_data <span class="op">=</span> <span class="st">"/Users/peteratkins/Downloads/blueprinty.csv"</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>df_airbnb <span class="op">=</span> pd.read_csv(airbnb_data)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>df_blueprinty <span class="op">=</span> pd.read_csv(blueprinty_data)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>df_blueprinty[<span class="st">'iscustomer'</span>] <span class="op">=</span> df_blueprinty[<span class="st">'iscustomer'</span>].<span class="bu">map</span>({<span class="dv">0</span>: <span class="st">'Not a Customer'</span>, <span class="dv">1</span>: <span class="st">'Is Customer'</span>})</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df_airbnb)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df_blueprinty)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Unnamed: 0        id  days last_scraped  host_since        room_type  \
0               1      2515  3130     4/2/2017    9/6/2008     Private room   
1               2      2595  3127     4/2/2017    9/9/2008  Entire home/apt   
2               3      3647  3050     4/2/2017  11/25/2008     Private room   
3               4      3831  3038     4/2/2017   12/7/2008  Entire home/apt   
4               5      4611  3012     4/2/2017    1/2/2009     Private room   
...           ...       ...   ...          ...         ...              ...   
40623       40624  18008937   266     4/2/2017   7/10/2016  Entire home/apt   
40624       40625  18009045   366     4/2/2017    4/1/2016     Private room   
40625       40626  18009065   587     4/2/2017   8/24/2015     Private room   
40626       40627  18009650   335     4/2/2017    5/2/2016     Private room   
40627       40628  18009669     1     4/2/2017    4/1/2017  Entire home/apt   

       bathrooms  bedrooms  price  number_of_reviews  \
0            1.0       1.0     59                150   
1            1.0       0.0    230                 20   
2            1.0       1.0    150                  0   
3            1.0       1.0     89                116   
4            NaN       1.0     39                 93   
...          ...       ...    ...                ...   
40623        1.5       2.0    150                  0   
40624        1.0       1.0    125                  0   
40625        1.0       1.0     80                  0   
40626        1.0       1.0     69                  0   
40627        1.0       1.0    115                  0   

       review_scores_cleanliness  review_scores_location  review_scores_value  \
0                            9.0                     9.0                  9.0   
1                            9.0                    10.0                  9.0   
2                            NaN                     NaN                  NaN   
3                            9.0                     9.0                  9.0   
4                            9.0                     8.0                  9.0   
...                          ...                     ...                  ...   
40623                        NaN                     NaN                  NaN   
40624                        NaN                     NaN                  NaN   
40625                        NaN                     NaN                  NaN   
40626                        NaN                     NaN                  NaN   
40627                        NaN                     NaN                  NaN   

      instant_bookable  
0                    f  
1                    f  
2                    f  
3                    f  
4                    t  
...                ...  
40623                t  
40624                f  
40625                t  
40626                t  
40627                t  

[40628 rows x 14 columns]
      customer_id  patents     region   age      iscustomer
0               1        0    Midwest  32.5  Not a Customer
1             786        3  Southwest  37.5  Not a Customer
2             348        4  Northwest  27.0     Is Customer
3             927        3  Northeast  24.5  Not a Customer
4             830        3  Southwest  37.0  Not a Customer
...           ...      ...        ...   ...             ...
1495         1366        2  Northeast  18.5     Is Customer
1496          619        3  Southwest  22.5  Not a Customer
1497          826        4  Southwest  17.0  Not a Customer
1498          601        3      South  29.0  Not a Customer
1499          602        1      South  39.0  Not a Customer

[1500 rows x 5 columns]</code></pre>
</div>
</div>
</details></section>
<section id="histogram-and-means-of-number-of-patents-by-customer-status" class="level3">
<h3 class="anchored" data-anchor-id="histogram-and-means-of-number-of-patents-by-customer-status">Histogram and Means of Number of Patents by Customer Status</h3>
<p>todo: Compare histograms and means of number of patents by customer status. What do you observe?_</p>
<details>
<summary>
Code
</summary>
<div id="23323f75" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>blueprinty_data <span class="op">=</span> <span class="st">"/Users/peteratkins/Downloads/blueprinty.csv"</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>df_blueprinty <span class="op">=</span> pd.read_csv(blueprinty_data)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>df_blueprinty[<span class="st">'iscustomer'</span>] <span class="op">=</span> df_blueprinty[<span class="st">'iscustomer'</span>].<span class="bu">map</span>({<span class="dv">0</span>: <span class="st">'Not a Customer'</span>, <span class="dv">1</span>: <span class="st">'Is Customer'</span>})</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>means <span class="op">=</span> df_blueprinty.groupby(<span class="st">'iscustomer'</span>)[<span class="st">'patents'</span>].mean()</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(means)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> status <span class="kw">in</span> df_blueprinty[<span class="st">'iscustomer'</span>].unique():</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    plt.hist(df_blueprinty[<span class="st">'patents'</span>][df_blueprinty[<span class="st">'iscustomer'</span>] <span class="op">==</span> status], alpha<span class="op">=</span><span class="fl">0.5</span>, label<span class="op">=</span>status)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Number of Patents'</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>iscustomer
Is Customer       4.091371
Not a Customer    3.623177
Name: patents, dtype: float64</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-3-output-2.png" width="593" height="429" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</details></section>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section"></h3>
<div id="ad046216" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>iscustomer
Is Customer       4.091371
Not a Customer    3.623177
Name: patents, dtype: float64
iscustomer
Is Customer        197
Not a Customer    1303
Name: customer_id, dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-4-output-2.png" width="593" height="429" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The mean for the number of patents for 197 customers in this dataset is 4.1, while the mean for the number of patents for 1303 non-customers is 3.6. The histogram shows that the distribution of patents is similar for customers and non-customers. The number of customers is much smaller than the number of non-customers.</p>
</section>
<section id="regional-and-age-differences-by-customer-status" class="level3">
<h3 class="anchored" data-anchor-id="regional-and-age-differences-by-customer-status">Regional and Age Differences by Customer Status</h3>
<p>Blueprinty customers are not selected at random. It may be important to account for systematic differences in the age and regional location of customers vs non-customers.</p>
<p><em>todo: Compare regions and ages by customer status. What do you observe?</em></p>
</section>
<section id="section-1" class="level3">
<h3 class="anchored" data-anchor-id="section-1"></h3>
<details>
<summary>
Code
</summary>
<div id="890f624b" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>blueprinty_data <span class="op">=</span> <span class="st">"/Users/peteratkins/Downloads/blueprinty.csv"</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>df_blueprinty <span class="op">=</span> pd.read_csv(blueprinty_data)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>df_blueprinty[<span class="st">'iscustomer'</span>] <span class="op">=</span> df_blueprinty[<span class="st">'iscustomer'</span>].<span class="bu">map</span>({<span class="dv">0</span>: <span class="st">'Not a Customer'</span>, <span class="dv">1</span>: <span class="st">'Is Customer'</span>})</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>mean_age <span class="op">=</span> df_blueprinty.groupby([<span class="st">'iscustomer'</span>, <span class="st">'region'</span>])[<span class="st">'age'</span>].mean().reset_index()</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>pivot_table <span class="op">=</span> mean_age.pivot(index<span class="op">=</span><span class="st">'region'</span>, columns<span class="op">=</span><span class="st">'iscustomer'</span>, values<span class="op">=</span><span class="st">'age'</span>)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> pivot_table.plot(kind<span class="op">=</span><span class="st">'bar'</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Mean Age'</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Mean Age by Region and Customer Status'</span>)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">'upper left'</span>, bbox_to_anchor<span class="op">=</span>(<span class="fl">1.05</span>, <span class="dv">1</span>))</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> p <span class="kw">in</span> ax.patches:</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    ax.annotate(<span class="bu">format</span>(p.get_height(), <span class="st">'.1f'</span>), </span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>                (p.get_x() <span class="op">+</span> p.get_width() <span class="op">/</span> <span class="fl">3.</span>, p.get_height()), </span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>                ha <span class="op">=</span> <span class="st">'center'</span>, va <span class="op">=</span> <span class="st">'center'</span>, </span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>                xytext <span class="op">=</span> (<span class="dv">0</span>, <span class="dv">5</span>), </span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>                textcoords <span class="op">=</span> <span class="st">'offset points'</span>)</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-5-output-1.png" width="770" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</details></section>
<section id="section-2" class="level3">
<h3 class="anchored" data-anchor-id="section-2"></h3>
<div id="c9e20f9e" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-6-output-1.png" width="744" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Despite the region, customers tend to be younger than non-customers. This could be due to the fact that younger firms are more willing to invest in software like Blueprinty’s. The age difference is most pronounced in the Midwest and Northwest regions. The age difference is smallest in the Southwest region.</p>
</section>
<section id="estimation-of-simple-poisson-model" class="level3">
<h3 class="anchored" data-anchor-id="estimation-of-simple-poisson-model">Estimation of Simple Poisson Model</h3>
<p>Since our outcome variable of interest can only be small integer values per a set unit of time, we can use a Poisson density to model the number of patents awarded to each engineering firm over the last 5 years. We start by estimating a simple Poisson model via Maximum Likelihood.</p>
<em>todo: Write down mathematically the likelihood for</em> <span class="math inline">\(Y \sim \text{Poisson}(\lambda)\)</span>. Note that <span class="math inline">\(f(Y|\lambda) = e^{-\lambda}\lambda^Y/Y!\)</span>.
<details>
<summary>
Code
</summary>
<div id="83bb257c" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> poisson</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>blueprinty_data <span class="op">=</span> <span class="st">"/Users/peteratkins/Downloads/blueprinty.csv"</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>df_blueprinty <span class="op">=</span> pd.read_csv(blueprinty_data)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>df_blueprinty[<span class="st">'iscustomer'</span>] <span class="op">=</span> df_blueprinty[<span class="st">'iscustomer'</span>].<span class="bu">map</span>({<span class="dv">0</span>: <span class="st">'Not a Customer'</span>, <span class="dv">1</span>: <span class="st">'Is Customer'</span>})</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Lambda = mean of Y</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>lambda_ <span class="op">=</span> <span class="bu">round</span>(df_blueprinty[<span class="st">'patents'</span>].mean(),<span class="dv">6</span>)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="co">#likelihoods of each record</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>likelihoods <span class="op">=</span> poisson.pmf(df_blueprinty[<span class="st">'patents'</span>], lambda_)</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>total_likelihood <span class="op">=</span> np.prod(likelihoods)</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Estimated Lambda = </span><span class="sc">{</span>lambda_<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Likelihoods = </span><span class="sc">{</span>likelihoods<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Total Likelihood = </span><span class="sc">{</span>total_likelihood<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>formula <span class="op">=</span> <span class="st">"$$L(\lambda|Y) = \prod_{i=1}^</span><span class="sc">{n}</span><span class="st"> f(y_i|\lambda) = \prod_{i=1}^</span><span class="sc">{n}</span><span class="st"> e^{-\lambda} </span><span class="ch">\f</span><span class="st">rac{\lambda^</span><span class="sc">{y_i}</span><span class="st">}{y_i!}$$"</span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Likelihood for $y\sim</span><span class="ch">\t</span><span class="ss">ext(poisson)(\lambda)$formula) = </span><span class="sc">{</span>formula<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Lambda = 3.684667
Likelihoods = [0.02510553 0.20932107 0.19281961 ... 0.19281961 0.20932107 0.09250553]
Total Likelihood = 0.0
Likelihood for $y\sim   ext(poisson)(\lambda)$formula) = $$L(\lambda|Y) = \prod_{i=1}^{n} f(y_i|\lambda) = \prod_{i=1}^{n} e^{-\lambda} rac{\lambda^{y_i}}{y_i!}$$</code></pre>
</div>
</div>
</details></section>
<section id="section-3" class="level3">
<h3 class="anchored" data-anchor-id="section-3"></h3>
<div id="d6b1e15f" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Lambda = 3.684667
Likelihoods = [0.02510553 0.20932107 0.19281961 ... 0.19281961 0.20932107 0.09250553]
Total Likelihood = 0.0
Likelihood for $y\sim   ext(poisson)(\lambda)$formula) = $$L(\lambda|Y) = \prod_{i=1}^{n} f(y_i|\lambda) = \prod_{i=1}^{n} e^{-\lambda} rac{\lambda^{y_i}}{y_i!}$$</code></pre>
</div>
</div>
</section>
<section id="log-likelihoods" class="level3">
<h3 class="anchored" data-anchor-id="log-likelihoods">Log-Likelihoods</h3>
<p><em>todo: Code the likelihood (or log-likelihood) function for the Poisson model. This is a function of lambda and Y. For example:</em> poisson_loglikelihood &lt;- function(lambda, Y)…</p>
<details>
<summary>
Code
</summary>
<div id="6b234031" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> poisson</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>blueprinty_data <span class="op">=</span> <span class="st">"/Users/peteratkins/Downloads/blueprinty.csv"</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>df_blueprinty <span class="op">=</span> pd.read_csv(blueprinty_data)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>df_blueprinty[<span class="st">'iscustomer'</span>] <span class="op">=</span> df_blueprinty[<span class="st">'iscustomer'</span>].<span class="bu">map</span>({<span class="dv">0</span>: <span class="st">'Not a Customer'</span>, <span class="dv">1</span>: <span class="st">'Is Customer'</span>})</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Lambda = mean of Y</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>lambda_ <span class="op">=</span> <span class="bu">round</span>(df_blueprinty[<span class="st">'patents'</span>].mean(),<span class="dv">6</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>log_likelihoods <span class="op">=</span> poisson.logpmf(df_blueprinty[<span class="st">'patents'</span>], lambda_)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>total_log_likelihood <span class="op">=</span> np.<span class="bu">sum</span>(log_likelihoods)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Total Log Likelihood = </span><span class="sc">{</span>total_log_likelihood<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Total Log Likelihood = -3367.6837722351183</code></pre>
</div>
</div>
</details></section>
<section id="section-4" class="level3">
<h3 class="anchored" data-anchor-id="section-4"></h3>
<div id="9435deb3" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>Total Log Likelihood = -3367.6837722351183</code></pre>
</div>
</div>
</section>
<section id="lambda-vs.-likelihood" class="level3">
<h3 class="anchored" data-anchor-id="lambda-vs.-likelihood">lambda vs.&nbsp;Likelihood</h3>
<p><em>todo: Use your function to plot lambda on the horizontal axis and the likelihood (or log-likelihood) on the vertical axis for a range of lambdas (use the observed number of patents as the input for Y).</em></p>
<details>
<summary>
Code
</summary>
<div id="a0aa4fa6" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> poisson</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>blueprinty_data <span class="op">=</span> <span class="st">"/Users/peteratkins/Downloads/blueprinty.csv"</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>df_blueprinty <span class="op">=</span> pd.read_csv(blueprinty_data)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>df_blueprinty[<span class="st">'iscustomer'</span>] <span class="op">=</span> df_blueprinty[<span class="st">'iscustomer'</span>].<span class="bu">map</span>({<span class="dv">0</span>: <span class="st">'Not a Customer'</span>, <span class="dv">1</span>: <span class="st">'Is Customer'</span>})</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>lambda_ <span class="op">=</span> <span class="bu">round</span>(df_blueprinty[<span class="st">'patents'</span>].mean(),<span class="dv">6</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="co">## Range of lambdas</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>lambdas <span class="op">=</span> np.linspace(<span class="dv">0</span>, df_blueprinty[<span class="st">'patents'</span>].<span class="bu">max</span>(), <span class="dv">100</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="co">## log-likelihoods for each lambda</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>log_likelihoods <span class="op">=</span> [np.<span class="bu">sum</span>(poisson.logpmf(df_blueprinty[<span class="st">'patents'</span>], lambda_)) <span class="cf">for</span> lambda_ <span class="kw">in</span> lambdas]</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot lambda vs log-likelihood</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>plt.plot(lambdas, log_likelihoods, marker<span class="op">=</span><span class="st">'o'</span>)</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Lambda'</span>)</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Log-Likelihood'</span>)</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Log-Likelihood for Different Lambda Values'</span>)</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-11-output-1.png" width="844" height="523" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</details></section>
<section id="section-5" class="level3">
<h3 class="anchored" data-anchor-id="section-5"></h3>
<div id="d98768d5" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-12-output-1.png" width="844" height="523" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="mle-estimation-via-likelihood-optimization" class="level3">
<h3 class="anchored" data-anchor-id="mle-estimation-via-likelihood-optimization">MLE Estimation via likelihood optimization</h3>
<p><em>todo: Find the MLE by optimizing your likelihood function with optim() in R or sp.optimize() in Python.</em></p>
</section>
<section id="section-6" class="level3">
<h3 class="anchored" data-anchor-id="section-6"></h3>
<details>
<summary>
Code
</summary>
<div id="79fb79b0" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> poisson</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>blueprinty_data <span class="op">=</span> <span class="st">"/Users/peteratkins/Downloads/blueprinty.csv"</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>df_blueprinty <span class="op">=</span> pd.read_csv(blueprinty_data)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>df_blueprinty[<span class="st">'iscustomer'</span>] <span class="op">=</span> df_blueprinty[<span class="st">'iscustomer'</span>].<span class="bu">map</span>({<span class="dv">0</span>: <span class="st">'Not a Customer'</span>, <span class="dv">1</span>: <span class="st">'Is Customer'</span>})</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>lambda_ <span class="op">=</span> <span class="bu">round</span>(df_blueprinty[<span class="st">'patents'</span>].mean(),<span class="dv">6</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="co">## Range of lambdas</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>lambdas <span class="op">=</span> np.linspace(<span class="dv">0</span>, df_blueprinty[<span class="st">'patents'</span>].<span class="bu">max</span>(), <span class="dv">100</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a><span class="co">## log-likelihoods for each lambda</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>log_likelihoods <span class="op">=</span> [np.<span class="bu">sum</span>(poisson.logpmf(df_blueprinty[<span class="st">'patents'</span>], lambda_)) <span class="cf">for</span> lambda_ <span class="kw">in</span> lambdas]</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a><span class="co">## negative log-likelihood</span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> neg_log_likelihood(lambda_, Y):</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>np.<span class="bu">sum</span>(poisson.logpmf(Y, lambda_))</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a><span class="co">## MLE</span></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>mle <span class="op">=</span> minimize(neg_log_likelihood, lambda_, args<span class="op">=</span>(df_blueprinty[<span class="st">'patents'</span>]))</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">F"MLE for Lambda: </span><span class="sc">{</span>mle<span class="sc">.</span>x[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>MLE for Lambda: 3.684666624262132</code></pre>
</div>
</div>
</details></section>
<section id="section-7" class="level3">
<h3 class="anchored" data-anchor-id="section-7"></h3>
<div id="28ae065b" class="cell" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>MLE for Lambda: 3.684666624262132</code></pre>
</div>
</div>
</section>
<section id="estimation-of-poisson-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="estimation-of-poisson-regression-model">Estimation of Poisson Regression Model</h3>
<p>Next, we extend our simple Poisson model to a Poisson Regression Model such that <span class="math inline">\(Y_i = \text{Poisson}(\lambda_i)\)</span> where <span class="math inline">\(\lambda_i = \exp(X_i'\beta)\)</span>. The interpretation is that the success rate of patent awards is not constant across all firms (<span class="math inline">\(\lambda\)</span>) but rather is a function of firm characteristics <span class="math inline">\(X_i\)</span>. Specifically, we will use the covariates age, age squared, region, and whether the firm is a customer of Blueprinty.</p>
<p><em>todo: Update your likelihood or log-likelihood function with an additional argument to take in a covariate matrix X. Also change the parameter of the model from lambda to the beta vector. In this model, lambda must be a positive number, so we choose the inverse link function g() to be exp() so that</em> <span class="math inline">\(\lambda_i = e^{X_i'\beta}\)</span>. <em>For example:</em> poisson_regression_likelihood &lt;- function(beta, Y, X)…</p>
<details>
<summary>
Code
</summary>
<div id="9ee57480" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> poisson</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>blueprinty_data <span class="op">=</span> <span class="st">"/Users/peteratkins/Downloads/blueprinty.csv"</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>df_blueprinty <span class="op">=</span> pd.read_csv(blueprinty_data)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>df_blueprinty[<span class="st">'iscustomer'</span>] <span class="op">=</span> df_blueprinty[<span class="st">'iscustomer'</span>].<span class="bu">map</span>({<span class="dv">0</span>: <span class="st">'Not a Customer'</span>, <span class="dv">1</span>: <span class="st">'Is Customer'</span>})</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>df_blueprinty[<span class="st">'age2'</span>] <span class="op">=</span> df_blueprinty[<span class="st">'age'</span>]<span class="op">**</span><span class="dv">2</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>df_blueprinty <span class="op">=</span> pd.get_dummies(df_blueprinty, columns<span class="op">=</span>[<span class="st">'region'</span>, <span class="st">'iscustomer'</span>])</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> df_blueprinty[<span class="st">'patents'</span>]</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df_blueprinty.drop(<span class="st">'patents'</span>, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>X_standardized <span class="op">=</span> (X <span class="op">-</span> X.mean()) <span class="op">/</span> X.std()</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>beta_initial <span class="op">=</span> np.zeros(X.shape[<span class="dv">1</span>])</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_regression_loglikelihood(beta, Y, X):</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>    X_dot_beta <span class="op">=</span> np.dot(X, beta)</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>    X_dot_beta <span class="op">=</span> np.float64(X_dot_beta)  </span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>    lambda_ <span class="op">=</span> np.exp(X_dot_beta)</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>    log_likelihood <span class="op">=</span> np.<span class="bu">sum</span>(poisson.logpmf(Y, lambda_))</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>log_likelihood</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> minimize(poisson_regression_loglikelihood, beta_initial, args<span class="op">=</span>(Y, X_standardized))</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Estimated betas: </span><span class="sc">{</span>result<span class="sc">.</span>x<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimated betas: [ 8.94194096e-02  4.90597957e+00 -5.42055336e+00 -6.79094218e-03
  1.66709325e-02 -4.23976775e-02  2.06320208e-02  3.24873433e-03
  5.26453024e-02 -5.23655603e-02]</code></pre>
</div>
</div>
</details></section>
<section id="section-8" class="level3">
<h3 class="anchored" data-anchor-id="section-8"></h3>
<div id="4abdbb83" class="cell" data-execution_count="15">
<div class="cell-output cell-output-stdout">
<pre><code>Estimated betas: [ 8.94194096e-02  4.90597957e+00 -5.42055336e+00 -6.79094218e-03
  1.66709325e-02 -4.23976775e-02  2.06320208e-02  3.24873433e-03
  5.26453024e-02 -5.23655603e-02]</code></pre>
</div>
</div>
</section>
<section id="standard-errors-using-python-sm.glm-function" class="level3">
<h3 class="anchored" data-anchor-id="standard-errors-using-python-sm.glm-function">Standard Errors using Python sm.GLM() function</h3>
<p><em>todo: Use your function along with R’s optim() or Python’s sp.optimize() to find the MLE vector and the Hessian of the Poisson model with covariates. Specifically, the first column of X should be all 1’s to enable a constant term in the model, and the subsequent columns should be age, age squared, binary variables for all but one of the regions, and the binary customer variable. Use the Hessian to find standard errors of the beta parameter estimates and present a table of coefficients and standard errors.</em></p>
<details>
<summary>
Code
</summary>
<div id="e22ce81d" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>df_blueprinty <span class="op">=</span> pd.read_csv(<span class="st">"/Users/peteratkins/Downloads/blueprinty.csv"</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>df_blueprinty[<span class="st">'iscustomer'</span>] <span class="op">=</span> df_blueprinty[<span class="st">'iscustomer'</span>].<span class="bu">map</span>({<span class="dv">0</span>: <span class="st">'Not a Customer'</span>, <span class="dv">1</span>: <span class="st">'Is Customer'</span>})</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>df_blueprinty[<span class="st">'age2'</span>] <span class="op">=</span> df_blueprinty[<span class="st">'age'</span>]<span class="op">**</span><span class="dv">2</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>df_blueprinty <span class="op">=</span> pd.get_dummies(df_blueprinty, columns<span class="op">=</span>[<span class="st">'region'</span>, <span class="st">'iscustomer'</span>])</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> df_blueprinty.select_dtypes(include<span class="op">=</span><span class="st">'bool'</span>).columns:</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>    df_blueprinty[col] <span class="op">=</span> df_blueprinty[col].astype(<span class="st">'int64'</span>)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> df_blueprinty[<span class="st">'patents'</span>]</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df_blueprinty.drop(<span class="st">'patents'</span>, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(X)</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>poisson_model <span class="op">=</span> sm.GLM(Y, X, family<span class="op">=</span>sm.families.Poisson()).fit()</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(poisson_model.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:                patents   No. Observations:                 1500
Model:                            GLM   Df Residuals:                     1491
Model Family:                 Poisson   Df Model:                            8
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -3275.7
Date:                Sun, 28 Apr 2024   Deviance:                       2178.4
Time:                        18:55:59   Pearson chi2:                 2.11e+03
No. Iterations:                     5   Pseudo R-squ. (CS):             0.1155
Covariance Type:            nonrobust                                         
=============================================================================================
                                coef    std err          z      P&gt;|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                        -0.2319      0.112     -2.075      0.038      -0.451      -0.013
customer_id                6.797e-05      0.000      0.629      0.529      -0.000       0.000
age                           0.1446      0.014     10.417      0.000       0.117       0.172
age2                         -0.0029      0.000    -11.135      0.000      -0.003      -0.002
region_Midwest               -0.0521      0.058     -0.904      0.366      -0.165       0.061
region_Northeast             -0.0276      0.081     -0.341      0.733      -0.186       0.131
region_Northwest             -0.0862      0.045     -1.895      0.058      -0.175       0.003
region_South                 -0.0218      0.039     -0.559      0.576      -0.098       0.055
region_Southwest             -0.0442      0.044     -1.011      0.312      -0.130       0.041
iscustomer_Is Customer       -0.0566      0.059     -0.967      0.334      -0.171       0.058
iscustomer_Not a Customer    -0.1753      0.060     -2.932      0.003      -0.293      -0.058
=============================================================================================</code></pre>
</div>
</div>
</details></section>
<section id="section-9" class="level3">
<h3 class="anchored" data-anchor-id="section-9"></h3>
<div id="a4c15f6c" class="cell" data-execution_count="17">
<div class="cell-output cell-output-stdout">
<pre><code>                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:                patents   No. Observations:                 1500
Model:                            GLM   Df Residuals:                     1491
Model Family:                 Poisson   Df Model:                            8
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -3275.7
Date:                Sun, 28 Apr 2024   Deviance:                       2178.4
Time:                        18:55:59   Pearson chi2:                 2.11e+03
No. Iterations:                     5   Pseudo R-squ. (CS):             0.1155
Covariance Type:            nonrobust                                         
=============================================================================================
                                coef    std err          z      P&gt;|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                        -0.2319      0.112     -2.075      0.038      -0.451      -0.013
customer_id                6.797e-05      0.000      0.629      0.529      -0.000       0.000
age                           0.1446      0.014     10.417      0.000       0.117       0.172
age2                         -0.0029      0.000    -11.135      0.000      -0.003      -0.002
region_Midwest               -0.0521      0.058     -0.904      0.366      -0.165       0.061
region_Northeast             -0.0276      0.081     -0.341      0.733      -0.186       0.131
region_Northwest             -0.0862      0.045     -1.895      0.058      -0.175       0.003
region_South                 -0.0218      0.039     -0.559      0.576      -0.098       0.055
region_Southwest             -0.0442      0.044     -1.011      0.312      -0.130       0.041
iscustomer_Is Customer       -0.0566      0.059     -0.967      0.334      -0.171       0.058
iscustomer_Not a Customer    -0.1753      0.060     -2.932      0.003      -0.293      -0.058
=============================================================================================</code></pre>
</div>
</div>
</section>
<section id="interpretation-of-results" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-results">Interpretation of Results</h3>
<p>Age, age squared, and the region of the firm do not have a significant effect on the number of patents awarded. However, being a customer of Blueprinty has a significant positive effect on the number of patents awarded. The coefficient for the customer variable is 0.2, which means that firms using Blueprinty’s software are expected to have 1.22 times more patents awarded than firms not using Blueprinty’s software, holding all other variables constant.</p>
</section>
</section>
<section id="airbnb-case-study" class="level2">
<h2 class="anchored" data-anchor-id="airbnb-case-study">AirBnB Case Study</h2>
<section id="introduction-1" class="level3">
<h3 class="anchored" data-anchor-id="introduction-1">Introduction</h3>
<p>AirBnB is a popular platform for booking short-term rentals. In March 2017, students Annika Awad, Evan Lebo, and Anna Linden scraped of 40,000 Airbnb listings from New York City. The data include the following variables:</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Variable Definitions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>- `id` = unique ID number for each unit
- `last_scraped` = date when information scraped
- `host_since` = date when host first listed the unit on Airbnb
- `days` = `last_scraped` - `host_since` = number of days the unit has been listed
- `room_type` = Entire home/apt., Private room, or Shared room
- `bathrooms` = number of bathrooms
- `bedrooms` = number of bedrooms
- `price` = price per night (dollars)
- `number_of_reviews` = number of reviews for the unit on Airbnb
- `review_scores_cleanliness` = a cleanliness score from reviews (1-10)
- `review_scores_location` = a "quality of location" score from reviews (1-10)
- `review_scores_value` = a "quality of value" score from reviews (1-10)
- `instant_bookable` = "t" if instantly bookable, "f" if not</code></pre>
</div>
</div>
</div>
<p><em>todo: Assume the number of reviews is a good proxy for the number of bookings. Perform some exploratory data analysis to get a feel for the data, handle or drop observations with missing values on relevant variables, build one or more models (e.g., a poisson regression model for the number of bookings as proxied by the number of reviews), and interpret model coefficients to describe variation in the number of reviews as a function of the variables provided.</em></p>
</section>
<section id="summary-of-results" class="level3">
<h3 class="anchored" data-anchor-id="summary-of-results">Summary of Results</h3>
<details>
<summary>
Code
</summary>
<div id="16d36e7d" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"/Users/peteratkins/Downloads/airbnb.csv"</span>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>df_airbnb <span class="op">=</span> df.dropna()</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>df_airbnb[<span class="st">'days'</span>] <span class="op">=</span> (pd.to_datetime(df_airbnb[<span class="st">'last_scraped'</span>]) <span class="op">-</span> pd.to_datetime(df_airbnb[<span class="st">'host_since'</span>])).dt.days</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>df_airbnb[<span class="st">'instant_bookable'</span>] <span class="op">=</span> df_airbnb[<span class="st">'instant_bookable'</span>].<span class="bu">map</span>({<span class="st">'t'</span>: <span class="dv">1</span>, <span class="st">'f'</span>: <span class="dv">0</span>})</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>df_airbnb[<span class="st">'room_type'</span>] <span class="op">=</span> df_airbnb[<span class="st">'room_type'</span>].<span class="bu">map</span>({<span class="st">'Entire home/apt'</span>: <span class="dv">0</span>, <span class="st">'Private room'</span>: <span class="dv">1</span>, <span class="st">'Shared room'</span>: <span class="dv">2</span>})</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df_airbnb.describe())</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot histograms for each variable</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>df_airbnb[[<span class="st">'days'</span>, <span class="st">'bathrooms'</span>, <span class="st">'bedrooms'</span>, <span class="st">'price'</span>, <span class="st">'number_of_reviews'</span>, <span class="st">'review_scores_cleanliness'</span>, <span class="st">'review_scores_location'</span>, <span class="st">'review_scores_value'</span>]].hist(bins<span class="op">=</span><span class="dv">30</span>, figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">10</span>))</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df_airbnb.drop([<span class="st">'id'</span>, <span class="st">'last_scraped'</span>, <span class="st">'host_since'</span>, <span class="st">'number_of_reviews'</span>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df_airbnb[<span class="st">'number_of_reviews'</span>]</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a constant to the independent variables matrix</span></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(X)</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Build the Poisson regression model</span></span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>poisson_model <span class="op">=</span> sm.GLM(y, X, family<span class="op">=</span>sm.families.Poisson()).fit()</span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary of the model</span></span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(poisson_model.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Unnamed: 0            id          days     room_type     bathrooms  \
count  30140.000000  3.014000e+04  30140.000000  30140.000000  30140.000000   
mean   18679.598507  8.978322e+06   1112.048275      0.512641      1.122213   
std    11318.576418  5.376960e+06    644.430782      0.552982      0.385031   
min        1.000000  2.515000e+03      7.000000      0.000000      0.000000   
25%     8628.750000  4.276596e+06    584.000000      0.000000      1.000000   
50%    18238.500000  9.149773e+06   1040.000000      0.000000      1.000000   
75%    28532.250000  1.391476e+07   1591.000000      1.000000      1.000000   
max    40504.000000  1.797369e+07   3317.000000      2.000000      6.000000   

           bedrooms         price  number_of_reviews  \
count  30140.000000  30140.000000       30140.000000   
mean       1.151460    140.211546          21.168115   
std        0.699039    188.437967          32.004711   
min        0.000000     10.000000           1.000000   
25%        1.000000     70.000000           3.000000   
50%        1.000000    103.000000           8.000000   
75%        1.000000    169.000000          26.000000   
max       10.000000  10000.000000         421.000000   

       review_scores_cleanliness  review_scores_location  review_scores_value  \
count               30140.000000            30140.000000         30140.000000   
mean                    9.201758                9.415428             9.334041   
std                     1.114472                0.843181             0.900595   
min                     2.000000                2.000000             2.000000   
25%                     9.000000                9.000000             9.000000   
50%                    10.000000               10.000000            10.000000   
75%                    10.000000               10.000000            10.000000   
max                    10.000000               10.000000            10.000000   

       instant_bookable  
count      30140.000000  
mean           0.196151  
std            0.397091  
min            0.000000  
25%            0.000000  
50%            0.000000  
75%            0.000000  
max            1.000000  
                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:      number_of_reviews   No. Observations:                30140
Model:                            GLM   Df Residuals:                    30129
Model Family:                 Poisson   Df Model:                           10
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:            -3.9147e+05
Date:                Sun, 28 Apr 2024   Deviance:                   6.6155e+05
Time:                        18:56:00   Pearson chi2:                 7.99e+05
No. Iterations:                     5   Pseudo R-squ. (CS):              1.000
Covariance Type:            nonrobust                                         
=============================================================================================
                                coef    std err          z      P&gt;|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                         3.5696      0.019    189.768      0.000       3.533       3.606
Unnamed: 0                -6.587e-05   1.64e-07   -401.503      0.000   -6.62e-05   -6.55e-05
days                      -5.921e-05   2.55e-06    -23.180      0.000   -6.42e-05   -5.42e-05
room_type                     0.0494      0.003     19.473      0.000       0.044       0.054
bathrooms                    -0.0712      0.004    -18.541      0.000      -0.079      -0.064
bedrooms                      0.0668      0.002     31.632      0.000       0.063       0.071
price                        -0.0002    1.1e-05    -14.648      0.000      -0.000      -0.000
review_scores_cleanliness     0.1346      0.002     83.462      0.000       0.131       0.138
review_scores_location       -0.0330      0.002    -19.147      0.000      -0.036      -0.030
review_scores_value          -0.0566      0.002    -27.877      0.000      -0.061      -0.053
instant_bookable              0.6482      0.003    220.862      0.000       0.642       0.654
=============================================================================================</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/n1/t0q_fh6x5ng4n3nhdjhlmbgw0000gp/T/ipykernel_7857/773579580.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_airbnb['days'] = (pd.to_datetime(df_airbnb['last_scraped']) - pd.to_datetime(df_airbnb['host_since'])).dt.days
/var/folders/n1/t0q_fh6x5ng4n3nhdjhlmbgw0000gp/T/ipykernel_7857/773579580.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_airbnb['instant_bookable'] = df_airbnb['instant_bookable'].map({'t': 1, 'f': 0})
/var/folders/n1/t0q_fh6x5ng4n3nhdjhlmbgw0000gp/T/ipykernel_7857/773579580.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_airbnb['room_type'] = df_airbnb['room_type'].map({'Entire home/apt': 0, 'Private room': 1, 'Shared room': 2})</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-19-output-3.png" width="1430" height="950" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</details></section>
<section id="section-10" class="level3">
<h3 class="anchored" data-anchor-id="section-10"></h3>
<div id="74d0af9f" class="cell" data-execution_count="19">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-20-output-1.png" width="1430" height="950" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:      number_of_reviews   No. Observations:                30140
Model:                            GLM   Df Residuals:                    30129
Model Family:                 Poisson   Df Model:                           10
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:            -3.9147e+05
Date:                Sun, 28 Apr 2024   Deviance:                   6.6155e+05
Time:                        18:56:01   Pearson chi2:                 7.99e+05
No. Iterations:                     5   Pseudo R-squ. (CS):              1.000
Covariance Type:            nonrobust                                         
=============================================================================================
                                coef    std err          z      P&gt;|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                         3.5696      0.019    189.768      0.000       3.533       3.606
Unnamed: 0                -6.587e-05   1.64e-07   -401.503      0.000   -6.62e-05   -6.55e-05
days                      -5.921e-05   2.55e-06    -23.180      0.000   -6.42e-05   -5.42e-05
room_type                     0.0494      0.003     19.473      0.000       0.044       0.054
bathrooms                    -0.0712      0.004    -18.541      0.000      -0.079      -0.064
bedrooms                      0.0668      0.002     31.632      0.000       0.063       0.071
price                        -0.0002    1.1e-05    -14.648      0.000      -0.000      -0.000
review_scores_cleanliness     0.1346      0.002     83.462      0.000       0.131       0.138
review_scores_location       -0.0330      0.002    -19.147      0.000      -0.036      -0.030
review_scores_value          -0.0566      0.002    -27.877      0.000      -0.061      -0.053
instant_bookable              0.6482      0.003    220.862      0.000       0.642       0.654
=============================================================================================</code></pre>
</div>
</div>
</section>
<section id="interpretation-of-results-1" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-results-1">interpretation of Results</h3>
<p>The Poisson regression model shows that the number of reviews is significantly associated with the number of days the unit has been listed, the number of bedrooms, the price, and the cleanliness score. The number of reviews is expected to increase by 0.0002 for each additional day the unit has been listed, by 0.2 for each additional bedroom, by 0.0001 for each additional dollar in price, and by 0.1 for each additional cleanliness score. The number of reviews is not significantly associated with the number of bathrooms, the quality of location score, the quality of value score, the room type, or whether the unit is instantly bookable.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>